#!/bin/bash

web_service='haproxy'
#config_file='/usr/local/etc/le-renew-haproxy.ini'
domain="firstary.xicp.net"
http_01_port='54321'
combined_file="/home/eyu/docker/haproxy/certs/${domain}.pem"

le_path='/usr/bin/certbot'
exp_limit=30;


cert_file="/etc/letsencrypt/live/$domain/fullchain.pem"
key_file="/etc/letsencrypt/live/$domain/privkey.pem"

if [ ! -f $cert_file ]; then
	echo "[ERROR] certificate file not found for domain $domain."
fi

exp=$(date -d "`openssl x509 -in $cert_file -text -noout|grep "Not After"|cut -c 25-`" +%s)
datenow=$(date -d "now" +%s)
days_exp=$(echo \( $exp - $datenow \) / 86400 |bc)

echo "Checking expiration date for $domain..."

if [ "$days_exp" -gt "$exp_limit" ] ; then
	echo "The certificate is up to date, no need for renewal ($days_exp days left)."
	exit 0;
else
	echo "The certificate for $domain is about to expire soon. Starting Let's Encrypt (HAProxy:$http_01_port) renewal script..."
	$le_path certonly --agree-tos --renew-by-default --standalone-supported-challenges http-01 --http-01-port $http_01_port -d $domain --standalone

	echo "Creating $combined_file with latest certs..."
	sudo bash -c "cat /etc/letsencrypt/live/$domain/fullchain.pem /etc/letsencrypt/live/$domain/privkey.pem > $combined_file"

	echo "Reloading $web_service"
	docker kill -s HUP haproxy
	echo "Renewal process finished for domain $domain"
	exit 0;
fi
